import Firebase from "@/lib/Firebase/index";
import type { Metadata } from "next";
import { Lato } from "next/font/google"
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const LatoFont = Lato({weight: "400", subsets: ['latin'], variable: '--font-caption'})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${LatoFont.variable} font-primary`}>
        <Firebase>{children}</Firebase>
      </body>
    </html>
  );
}
